### ISSUE TITLE
Files with 0 bytes (file length) are ignored. Should not be ignored.

### ISSUE THREAD

**Issue by Wikinaut** [pixelb/fslint#105]
I noticed, that files with zero bytes are ignored (skipped) when looking for doublures. This is regarded as a bug (I as user want to detect doublures of zero-length files , too).

**Comment by pixelb** [comment]
Hrm, well the reasoning is that generally such files would be flags etc. rather than having significant content. It would have to be an option if supported

**Comment by Wikinaut** [comment]
@pixelb write
> well the reasoning is that generally such files would be flags etc. rather than having significant content. It would have to be an option if supported

I don't think so. In my view, these zero-length files should be treated as any other file with the same content.

I noticed them, because after comparing two paths /copy1 and /copy2 and deleting the doublures in /copy2, the /copy2 path still has hundreds of files, zero-length files, but all are doublures of existing and wanted zero-length files in /copy1.

When I have /copy1/thisflag1 and /copy2/thisflag2, these files are doublures - they both have 0 bytes and are to be reported in the group of files with the same content (same hash(0)).

Then I can deleted the non-first file after selecting it (which is what I want).

I have nothing against an option (default=active, i.e. zero-length files should be treated as any other file).
