### ISSUE TITLE
Empty directory search gives false-positive results: directories are found which were not empty because of */.git or similar items

### ISSUE THREAD

**Issue by Wikinaut** [pixelb/fslint#106]
I used the function to identify empty directories. A list is presented. Now I select all and want to delete them all.

This fails because of the

#### Bug
Some directories which were found "empty" are not empty because they contain .git or .svn items.

**Comment by pixelb** [comment]
Hmm we probably should ignore the "paths to exclude" settings for the "Empty dirs" function.
