### ISSUE TITLE
suggestion: change "Minimum size" to "Minimum file size" 

### ISSUE THREAD

**Issue by Wikinaut** [pixelb/fslint#109]
The new text is not clear, it should read "minimum file size" or "minimum file length"

And the default value should be 0, not 1.

**Comment by pixelb** [comment]
I disagree on the default. I've amended the label.

**Comment by Wikinaut** [comment]
Is there a way (other than to modify the source) to set such a default value in a kind of .fslint config file ? I could not find anything like that.

**Comment by pixelb** [comment]
Not at present (see issue #12)

**Comment by Wikinaut** [comment]
see doc/news file: "* findup now includes zero length files by default."

This new comment is in contradiction to what you said above ("I disagree on the default." (minimum file size == 0)

**Comment by pixelb** [comment]
The lower level findup script includes zero length files by default.
The GUI defaults to excluding them (min_size == 1)
