### ISSUE TITLE
Supporting the project with bitcoin donations

### ISSUE THREAD

**Issue by Wikinaut** [pixelb/fslint#110]
I want to support your work and the projects by sending you a bitcoin donation.

Perhaps you want to add your receiving address (and a QR code) somewhere here in your github profile, or somewhere else on your regular website?

**Comment by pixelb** [comment]
That's very generous, but not needed. The best way you can support is to keep up the excellent bug reports etc. Thanks!

**Comment by Wikinaut** [comment]
ok
