### ISSUE TITLE
".IndexError: list index out of range" when deleting duplicated files (only if last file is selected)

### ISSUE THREAD

**Issue by fanatixx** [pixelb/fslint#112]
Hello,

Today, while deleting a large amount of duplicate files, the message ".IndexError: list index out of range" was displayed in the traceback (see bellow), and fslint-gui didn't do anything (not even displayed a GUI error message). It only worked after I de-selected the last file in the list, what indicates that it is some problem with one of the arrays used in the process.

=================================================
raphael@QBex:~$ uname -a
Linux QBex 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
=================================================
raphael@QBex:~$ python --version
Python 2.7.9
=================================================
raphael@QBex:~$ fslint-gui --version
FSlint 2.44
=================================================
Traceback (most recent call last):
  File "/usr/bin/fslint-gui", line 1773, in on_delSelected_clicked
    self.find_group_with_all_selected(skip_groups):
  File "/usr/bin/fslint-gui", line 1650, in find_group_with_all_selected
    if group_all_selected(clist, row):
  File "/usr/bin/fslint-gui", line 1641, in group_all_selected
    while get_selectable(row, row_data) and row < clist.rows:
  File "/usr/bin/fslint-gui", line 421, in get_selectable
    return row_data[row][0] != '#'
IndexError: list index out of range

**Comment by pixelb** [comment]
Fixed already with commit b3a64bb9
You can use the latest trunk version like

    git clone https://github.com/pixelb/fslint.git
    cd fslint
    (cd po && make)
    ./fslint-gui

I plan to cut a release soon
