### ISSUE TITLE
findup false-positives

### ISSUE THREAD

**Issue by ofbgh** [pixelb/fslint#117]
I've found with large directories, findup -t can list merge-candidates that are already sharing the same inode.

The 'large directories' are >400MB backup snapshots created with 
rsync -a -H -x -q --delete --link-dest=/path/to/PreviousBackup/ /Source/ /path/to/FreshBackup/

The first surprise results came from comparing two backups.

So then I used findup -t on a different pair of backups, and got the same false-positive merge-candidates.

Next I extracted just one false-positive pair, and ran findup -t on them alone. This time findup correctly did not suggest merging.

Then I replaced the files, then extracted & tested only their branch. and got the false-positive report. I continued reducing the size of the branch and getting false-positives, right down to the containing directories of the pair.

Eventually I found i could extract only the pair, plus just one of three particular sibling files, and that would be enough to trigger the false-positive report.

I cannot imagine why this would happen, or why these siblings could be 'catalysts' for the bug, yet not other siblings.

FWIW there is nothing strange about any of the files. In this case they were all perfectly normal images with names like 'img008.bmp'.

I am very sorry i cannot make a more clear bug report of this. I am completely baffled, and cannot think of how to dissect it more usefully. 

fslint 2.44-1 (trusty) on Mint 17.

**Comment by pixelb** [comment]
So you've simplified it to 5 files that trigger the issue?
Could you send the output of `find . -printf '%D:%i %s\t%f\n'` for those 5 files.
Also the output from md5sum and sha1sum would be useful for those files.

To directly debug the issue you could add `| tee /tmp/issue_117.tmp` lines
to the findup shell script, to see the output at each stage (while running
the script on those 5 files).

**Comment by ofbgh** [comment]
Hi. Sorry I am not clear enough. I am saying I have selected just one of the false-positive pairs to experiment on, and I found three sibling files whose presence trigger that false-positive report.

Without these files, there is no false-positive report for this pair. Also it only requires one of these three files to be present to trigger the report.


n@glam /media/n/1000/o/findup $ find . -printf '%D:%i %s\t%f\n'
64515:25714759 4096	.
64515:30277640 12192822	img010.bmp
64515:30277634 12192822	img002.bmp
64515:30277636 12192822	img006.bmp
64515:25706568 4096	B
64515:30277638 12192822	img008.bmp
64515:25706567 4096	A
64515:30277638 12192822	img008.bmp


Please excuse my ignorance: but is this the correct way? I can't get it to work with pipes both fore & aft like you've asked.

n@glam /media/n/1000/o/findup $ /usr/share/fslint/fslint/findup -t . | tee /tmp/issue_117.tmp
A/img008.bmp
B/img008.bmp

issue_117.tmp's full content is these two lines.
A/img008.bmp
B/img008.bmp

**Comment by ofbgh** [comment]
Cool. Thank you very much for this fast response & fix.

I'm relieved it's not a symptom of a deeper problem, so will stop worrying about using the merge function on my directories. (I'm also relieved to find out I'm not simply gone senile.)
