### ISSUE TITLE
findup merge can fail

### ISSUE THREAD

**Issue by ofbgh** [pixelb/fslint#118]
(Perhaps your fix for 117 also fixes this.)

findup merge fails when there is an unrelated file whose byte-size is identical to that of the merge-candidates.

demonstration:

n@glam ~/a52 $ find . -printf '%D:%i %s\t%f\n'
64513:7504055 4096	.
64513:7504057 4096	B
64513:7492423 8192	foo
64513:7504056 4096	A
64513:7492421 8192	SameSize
64513:7492418 8192	foo
n@glam ~/a52 $ /usr/share/fslint/fslint/findup -t .
A/foo
B/foo
n@glam ~/a52 $ /usr/share/fslint/fslint/findup -m .
n@glam ~/a52 $ /usr/share/fslint/fslint/findup -t .
A/foo
B/foo
n@glam ~/a52 $ find . -printf '%D:%i %s\t%f\n'
64513:7504055 4096	.
64513:7504057 4096	B
64513:7492418 8192	foo
64513:7504056 4096	A
64513:7492421 8192	SameSize
64513:7492418 8192	foo

/a52/A/foo
/a52/B/foo
/a52/SameSize

fslint 2.44-1 (trusty) on Mint 17

**Comment by pixelb** [comment]
Issue #117 would explain this if A/foo and B/foo were the same inode, but they're not.
I can't reproduce this. Note -t is for use with -m or -d.
Does `findup -m -t` print that it's performing any operations?

**Comment by ofbgh** [comment]
For sanity-check, I've repeated the process on my Mint 17 laptop as well. 

The files 'foo' and 'SameSize' are created this way
dd if=/dev/urandom of=foo  bs=1024  count=8 &> /dev/null


n@glam ~/a52 $ find . -printf '%D:%i %s\t%f\n'
64513:7504055 4096	.
64513:7504057 4096	B
64513:7492418 8192	foo
64513:7492421 8192	SameSize
64513:7504056 4096	A
64513:7492418 8192	foo
n@glam ~/a52 $ /usr/share/fslint/fslint/findup -m -t


keeping:     A/foo
hardlinking: B/foo n@glam ~/a52 $ /usr/share/fslint/fslint/findup -m
n@glam ~/a52 $ /usr/share/fslint/fslint/findup -m -t


keeping:     A/foo
hardlinking: B/foo n@glam ~/a52 $ find . -printf '%D:%i %s\t%f\n'
64513:7504055 4096	.
64513:7504057 4096	B
64513:7492418 8192	foo
64513:7492421 8192	SameSize
64513:7504056 4096	A
64513:7492418 8192	foo
n@glam ~/a52 $ 


![screenshot at 2016-01-12 14 00 31](https://cloud.githubusercontent.com/assets/8523807/12278277/0500a912-b935-11e5-8dba-a1a7e52f7cad.png)

**Comment by pixelb** [comment]
Right. -t only reports what it would do, so it looks like it would do the correct operations without the -t.
As I said above Issue #117 would explain this if A/foo and B/foo were the same inode, and in fact they are (I misread the inodes previously)

**Comment by ofbgh** [comment]
Ah. I misread too, incorrectly believing the second -t. Sorry about that, and thank you.
