### ISSUE TITLE
Two typos in finnish translation (patch)

### ISSUE THREAD

**Issue by aapo** [pixelb/fslint#120]
diff --git a/po/fi.po b/po/fi.po
    index ee4ae7d..e87219c 100644    
    --- a/po/fi.po
    +++ b/po/fi.po
    @@ -175,7 +175,7 @@ msgstr "Nimiristiriidat"
     
     #: ../fslint.glade:1587
     msgid "More restrictive search for core files"
    -msgstr "Rajoittavampi haku muistivedottiedostoille"
    +msgstr "Rajoittavampi haku muistivedostiedostoille"
     
     #: ../fslint.glade:1589
     msgid "core file mode?"
    @@ -446,7 +446,7 @@ msgstr " linkkejä"
     
     #: ../fslint-gui:929 ../fslint-gui:1045
     msgid " bytes wasted in "
    -msgstr " tarvua hukkakäytössä "
    +msgstr " tavua hukkakäytössä "
     
     #: ../fslint-gui:975 ../fslint-gui:1046
     msgid " files (in "

**Comment by pixelb** [comment]
https://translations.launchpad.net/fslint/trunk/+pots/fslint/fi is now in sync with this. Will sync soon. thanks
