### ISSUE TITLE
If the filename (and / or directoryname?) contains a pair of braces "()", fslint won't find it. 

### ISSUE THREAD

**Issue by ternet** [pixelb/fslint#125]
If one runs fslint with only a list of files as arguments and the files contailns braces, fslint can't find the files:

fslint -m ./FileOne.txt ./FileTwo.txt ./File(Three).txt

Greetings, Tobias

**Comment by pixelb** [comment]
I presume you mean `findup -m` rather than `fslint -m`?
Note the above command will merge duplicates silently.
Can you try again for separate files without the -m option?
I can't reproduce on latest trunk with `fslint/findup ./FileOne.txt ./FileTwo.txt ./File(Three).txt` at least?

**Comment by ternet** [comment]
Yes, of course findup and yes the braces don't produce the problem. Sorry for testing not thoroughly enough.  

Now I did some more test (also with the clone of https://github.com/pixelb/fslint.git): The problem is based on two or more spaces in the filename:

LANG=C findup -m Test\ 0.doc Test\ \ 1.doc Test\ \ \ 2.doc 
find: `Test 1.doc': No such file or directory
find: `Test 2.doc': No such file or directory
