### ISSUE TITLE
"Select from same folder" takes a very long time for big sets of matches

### ISSUE THREAD

**Issue by lucasw** [pixelb/fslint#126]
If I have more than 50,000-100,000 total duplicates found (I'm not sure about the that number, I'll add details here as I encounter this again), when I select from same folder the application takes 100% cpu for several minutes before selecting all the files from the same folder.  This is regardless of how many duplicates are in that particular folder (typically 100-500).

This is with version 2.44 installed on Ubuntu 16.04

**Comment by pixelb** [comment]
Was fixed with commit be14e913

**Comment by lucasw** [comment]
Cool, it looks like that is in the new 2.46 release https://github.com/pixelb/fslint/releases/tag/2.46
