### ISSUE TITLE
findsn : Cannot filter output through pipe

### ISSUE THREAD

**Issue by sebma** [pixelb/fslint#132]
Hi,

I want to filter the output of `findsn` to output the files belonging to me that is:

`$ findsn /datas/Videos/ | grep -z $USER`

Can you please add `| xargs -r0 ls -lbUd --color=auto --` at line 172 just before the `else` ?

Thank you for your comprehension.

**Comment by pixelb** [comment]
You could post process the findsn output directly like:

    findsn /datas/Videos/ | tr -s '\0' | xargs -r0 sh -c 'find "$@" -user $USER -ls'

But really you want to take advantage of the fact that you can pass extra find parameters to any of the fslint command line utilities to filter beforehand. I.E. you just need to:

    findsn /datas/Videos -user $USER

**Comment by sebma** [comment]
Thanks a lot for your answer, that solves my first problem.

My second problem is that in pipe mode (when topipe = yes), only the filename is displayed.

Therefore, if I want to sort the output by file size, it won't work:

`$ ./findsn /datas/Videos -name "*.mp4" -user $USER | sort -znrk5,5`

**Comment by pixelb** [comment]
For sophisticated processing like that you can mix both techniques

    ./findsn /datas/Videos -name '*.mp4' -user $USER |
    tr -s '\0' | xargs -r0 sh -c 'find "$@" -ls' | sort -k7,7nr | less

I should mention that "$0" is not used along with "$@" above there,
as the first entry is empty when piping output from findsn (to indicate a new group).
The `tr -s '\0'` is to remove the other group delimiters as it's not needed in this case.

**Comment by pixelb** [comment]
BTW it's strange to be matching file names and then ordering by size like this. Are you sure you don't want to look for duplicates using findup, which implicitly orders by size

    ./findup --summary /datas/Videos -name '*.mp4' -user $USER

**Comment by sebma** [comment]
I want to delete the bigger ones :)

**Comment by sebma** [comment]
I could type all this every time I need to see more information than the file name, but over time it can be a bit tiring.

Why not include `| xargs -r0 sh -c 'find "$@" -ls'` in your `findsn` script (line number 172) instead ?

I know I can modify my local copy on my own, but I would prefer to have the same version of your script on all the Linux machines.

**Comment by sebma** [comment]
Moreover, the big files I want to delete have the same name but not the same signature because some videos (previously downloaded didn't have the youtube subtitles or comments).

That's why I'm using `findsn`
