### ISSUE TITLE
Mint 20 installation doesn't work

### ISSUE THREAD

**Issue by ZerooCool** [pixelb/fslint#171]
```
sudo dpkg-buildpackage -I.git -rfakeroot -tc

dpkg-buildpackage: avertissement:     debian/changelog(l5): ignoring invalid week day 'wed'
LINE:  -- Pádraig Brady <P@draigBrady.com>  wed, 01 feb 2017 22:32:00 +0000
dpkg-buildpackage: avertissement: utilisation d'une commande pour obtenir les privilèges administrateur en tant qu'administrateur
dpkg-buildpackage: info: paquet source fslint
dpkg-buildpackage: info: version source 2.47-1
dpkg-buildpackage: info: distribution source unstable
dpkg-buildpackage: info: source changé par Pádraig Brady <P@draigBrady.com>
dpkg-buildpackage: info: architecture hôte amd64
 dpkg-source -I.git --before-build .
dpkg-source: avertissement: fslint-2.47/debian/changelog(l5): ignoring invalid week day 'wed'
LINE:  -- Pádraig Brady <P@draigBrady.com>  wed, 01 feb 2017 22:32:00 +0000
dpkg-checkbuilddeps: erreur: Unmet build dependencies: build-essential:native debhelper (>= 5)
dpkg-buildpackage: avertissement: dépendances de construction et conflits non satisfaits ; échec.
dpkg-buildpackage: avertissement: (Utilisez l'option -d pour forcer.)
```

**Comment by j-i-l** [comment]
You can `apt-get install build-essential debhelper` then the package will build.

HOWEVER, you will run into a `no module named gtk` error when running `fslint-gui` on your mint 20, which is because, as of now, fslint still depends on python2 and gtk2 (see #172 for an upcoming solution).

**Comment by j-i-l** [comment]
Might be solved with https://github.com/pixelb/fslint/issues/168#issuecomment-622287261

**Comment by ZerooCool** [comment]
Resolved with python2 :

mkdir -p ~/Downloads/fslint
cd ~/Downloads/fslint
wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-6_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/f/fslint/fslint_2.46-1_all.deb 
sudo apt-get install ./*.deb
