### ISSUE TITLE
Question related to the code

### ISSUE THREAD

**Issue by kadogo** [pixelb/fslint#176]
Hello,
Sorry bothering you by a question like that.

I was reading the code to understand how it works and `uniq -3 -D` is confusing because I not know this syntax. I read the manual and I can only guess `-3` is related to the inputs with sort but I really not understand where it's written and how it works. Are there some docs about it or maybe a proper name how it is called so that I can look it up further?

Thanks for your help and for fslint because it helped me good for cleaning few of my hard drives.
Cheers.

**Comment by pixelb** [comment]
fslint is old software now and was written to be
compatible with older implementations of uniq.
`uniq -3` is equivalent to `uniq -f 3` or `uniq --skip-fields=3`.

man pages generally don't document every detail,
like deprecated syntax like that.
man pages now do have a link at the end to the full documentation,
which does in this case detail this case.

I.e. the following link details this nuance:
https://www.gnu.org/software/coreutils/uniq
