### ISSUE TITLE
Create symlinks for duplicates

### ISSUE THREAD

**Issue by pixelb** [pixelb/fslint#42]
Original [issue 43](https://code.google.com/p/fslint/issues/detail?id=43) created by pixelb on 2010-01-26T13:13:20.000Z:

In the duplicates section, fslint can merge many files by creating a hard link.

Hard links avoid wasting disk space, but a copy on another area would need
another duplicates pass.

I prefer using (relative) symlinks which are copy-safe and somehow &quot;cleaner&quot;.

In addition to the Merge button, a Link button would be useful to link all
the non-selected elements to the selected one in a set.

**Comment by sixtyfive** [comment]
Hi! I'm looking for a way to softlink duplicates to their original. Has that ever become possible to do with fslint since the last message here?

**Comment by sixtyfive** [comment]
Well, that seems to answer the question. Thank you @pixelb!
