### ISSUE TITLE
fslint from SVN should have a different name than the official package

### ISSUE THREAD

**Issue by pixelb** [pixelb/fslint#77]
Original [issue 78](https://code.google.com/p/fslint/issues/detail?id=78) created by pixelb on 2012-04-14T23:43:34.000Z:

To avoid confusion fslint package built from SVN should have a different name than the official package.  Please consider to apply the following patch.

**Comment by leggewie** [comment]
By "official" package I assume the OP for this ticket over at google meant the Debian package.  I agree with the sentiment but I'm not sure if there is any real conflict between the version from git/svn and the one in Debian.  The patch provided certainly has some errors in it.  Do you understand why he was proposing it?

BTW, are we going to see another official release?  It's been so long...

**Comment by leggewie** [comment]
Or should I just go and release git-based packages to Debian?  It would help to have an official tag here and there, at least.

**Comment by pixelb** [comment]
There were a few fixes recently. I'll try to a release in a week or so...

**Comment by pixelb** [comment]
I just released:
http://www.pixelbeat.org/fslint/fslint-2.46.tar.xz
